Repository cintiabelenestrada/repo-tp2, pull requests merged in 2023-06, with the labels that each got.

#114 Agregado la Capa Servicio de Productos
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/controller/ProductListController.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/model/Product.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/service/IProductService.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/service/imp/ProductServiceImp.java
  tp2_Grupo44/src/main/resources/templates/layouts/header.html
  tp2_Grupo44/src/main/resources/templates/productos.html
  tp2_Grupo44/src/main/resources/templates/sucursales.html
Labels: Mejora

#120 Actualizar base del proyecto
  .prettierrc
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/controller/BranchOfficeController.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/controller/DogWalkingServiceController.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/controller/HealthTipController.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/controller/ProductListController.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/lists/HealthTipList.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/model/HealthTip.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/model/Product.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/service/IBranchService.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/service/ICommonService.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/service/IDogWalkerService.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/service/IHealthTipService.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/service/IProductService.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/service/imp/BranchServiceImp.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/service/imp/CommonServiceImp.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/service/imp/DogWalkerServiceImp.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/service/imp/HealthTipServiceImp.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/service/imp/ProductServiceImp.java
  tp2_Grupo44/src/main/resources/static/images/healttips/consejo0.jpg
  tp2_Grupo44/src/main/resources/static/images/healttips/consejo1.png
  tp2_Grupo44/src/main/resources/static/images/healttips/consejo2.jpg
  tp2_Grupo44/src/main/resources/static/images/healttips/consejo3.jpg
  tp2_Grupo44/src/main/resources/templates/consejos_de_salud.html
  tp2_Grupo44/src/main/resources/templates/contactanos.html
  tp2_Grupo44/src/main/resources/templates/index.html
  tp2_Grupo44/src/main/resources/templates/layouts/header.html
  tp2_Grupo44/src/main/resources/templates/nueva_sucursal.html
  tp2_Grupo44/src/main/resources/templates/nuevo_consejo_de_salud.html
  tp2_Grupo44/src/main/resources/templates/nuevo_paseador.html
  tp2_Grupo44/src/main/resources/templates/nuevo_producto.html
  tp2_Grupo44/src/main/resources/templates/productos.html
  tp2_Grupo44/src/main/resources/templates/sucursales.html
Labels: Mejora, Tarea

#121 CintiaEstrada- Bootstrap para Header
  tp2_Grupo44/src/main/resources/templates/layouts/header.html
Labels: Diseño

#127 Branch estrada cintia
  tp2_Grupo44/src/main/resources/templates/layouts/header.html
Labels: Diseño

#130 Estrada_Bootstrap_Productos_NuevoProducto_Modal
  tp2_Grupo44/src/main/resources/templates/nuevo_producto.html
  tp2_Grupo44/src/main/resources/templates/productos.html
Labels: Diseño

#128 Develop
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/controller/BranchOfficeController.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/controller/DogWalkingServiceController.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/controller/HealthTipController.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/controller/ProductListController.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/service/IBranchService.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/service/ICommonService.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/service/IDogWalkerService.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/service/IHealthTipService.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/service/imp/BranchServiceImp.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/service/imp/CommonServiceImp.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/service/imp/DogWalkerServiceImp.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/service/imp/HealthTipServiceImp.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/service/imp/ProductServiceImp.java
  tp2_Grupo44/src/main/resources/static/css/estilos.css
  tp2_Grupo44/src/main/resources/static/images/cahorro.jpg
  tp2_Grupo44/src/main/resources/static/images/conejos.jpg
  tp2_Grupo44/src/main/resources/static/images/gatitos.jpg
  tp2_Grupo44/src/main/resources/templates/consejos_de_salud.html
  tp2_Grupo44/src/main/resources/templates/contactanos.html
  tp2_Grupo44/src/main/resources/templates/index.html
  tp2_Grupo44/src/main/resources/templates/layouts/header.html
  tp2_Grupo44/src/main/resources/templates/nuevo_consejo_de_salud.html
  tp2_Grupo44/src/main/resources/templates/nuevo_paseador.html
  tp2_Grupo44/src/main/resources/templates/nuevo_producto.html
  tp2_Grupo44/src/main/resources/templates/productos.html
Labels: Diseño

#131 Actualizar proyecto
  .vscode/launch.json
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/controller/ProductListController.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/model/HealthTip.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/model/Image.java
  tp2_Grupo44/src/main/resources/static/css/estilos.css
  tp2_Grupo44/src/main/resources/templates/contactanos.html
  tp2_Grupo44/src/main/resources/templates/index.html
  tp2_Grupo44/src/main/resources/templates/nuevo_producto.html
Labels: Mejora, Tarea

#133 Cambios varios
  .vscode/launch.json
  tp2_Grupo44/bin/src/main/resources/static/NewFile.html
  tp2_Grupo44/bin/src/main/resources/templates/index.html
  tp2_Grupo44/src/main/resources/static/css/estilos.css
  tp2_Grupo44/src/main/resources/templates/consejos_de_salud.html
  tp2_Grupo44/src/main/resources/templates/contactanos.html
  tp2_Grupo44/src/main/resources/templates/index.html
  tp2_Grupo44/src/main/resources/templates/layouts/footer.html
  tp2_Grupo44/src/main/resources/templates/layouts/header.html
  tp2_Grupo44/src/main/resources/templates/nueva_sucursal.html
  tp2_Grupo44/src/main/resources/templates/nuevo_consejo_de_salud.html
  tp2_Grupo44/src/main/resources/templates/nuevo_paseador.html
  tp2_Grupo44/src/main/resources/templates/nuevo_producto.html
  tp2_Grupo44/src/main/resources/templates/productos.html
  tp2_Grupo44/src/main/resources/templates/servicio_de_paseos.html
  tp2_Grupo44/src/main/resources/templates/sucursales.html
Labels: Mejora, Tarea

#134 Actualizar main con los últimos cambios realizados
  tp2_Grupo44/bin/src/main/resources/static/NewFile.html
  tp2_Grupo44/bin/src/main/resources/templates/index.html
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/controller/ProductListController.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/model/HealthTip.java
  tp2_Grupo44/src/main/java/ar/edu/unju/fi/model/Image.java
  tp2_Grupo44/src/main/resources/static/css/estilos.css
  tp2_Grupo44/src/main/resources/templates/consejos_de_salud.html
  tp2_Grupo44/src/main/resources/templates/contactanos.html
  tp2_Grupo44/src/main/resources/templates/index.html
  tp2_Grupo44/src/main/resources/templates/layouts/footer.html
  tp2_Grupo44/src/main/resources/templates/layouts/header.html
  tp2_Grupo44/src/main/resources/templates/nueva_sucursal.html
  tp2_Grupo44/src/main/resources/templates/nuevo_consejo_de_salud.html
  tp2_Grupo44/src/main/resources/templates/nuevo_paseador.html
  tp2_Grupo44/src/main/resources/templates/nuevo_producto.html
  tp2_Grupo44/src/main/resources/templates/productos.html
  tp2_Grupo44/src/main/resources/templates/servicio_de_paseos.html
  tp2_Grupo44/src/main/resources/templates/sucursales.html
Labels: Tarea

#136 Limpieza del proyecto
  README.md
  tp2_Grupo44/bin/src/main/resources/static/images/alimento_gato.jpg
  tp2_Grupo44/bin/src/main/resources/static/images/alimento_perro.jpg
  tp2_Grupo44/bin/src/main/resources/static/images/casitas.jpg
  tp2_Grupo44/bin/src/main/resources/static/images/catnip.jpg
  tp2_Grupo44/bin/src/main/resources/static/images/food_animal.png
  tp2_Grupo44/bin/src/main/resources/static/images/frisbee.jpg
  tp2_Grupo44/bin/src/main/resources/static/images/gato_jugueton.jpeg
  tp2_Grupo44/bin/src/main/resources/static/images/gatos_cancheros.jpg
  tp2_Grupo44/bin/src/main/resources/static/images/gatos_con_campera.jpg
  tp2_Grupo44/bin/src/main/resources/static/images/interactivo.jpg
  tp2_Grupo44/bin/src/main/resources/static/images/juguetes3.jpeg
  tp2_Grupo44/bin/src/main/resources/static/images/juguetes4.jpg
  tp2_Grupo44/bin/src/main/resources/static/images/mascotas_ropa.jpg
  tp2_Grupo44/bin/src/main/resources/static/images/peluches.jpg
  tp2_Grupo44/bin/src/main/resources/static/images/perro_jugueton.jpg
  tp2_Grupo44/bin/src/main/resources/static/images/perros_juguetes.jpg
  tp2_Grupo44/bin/src/main/resources/static/images/rascador.jpg
  tp2_Grupo44/pom.xml
Labels: Tarea
